### ISSUE TITLE
Async/await implementation à la tink_await?

### ISSUE THREAD

**Issue by cambiata** [DenkiYagi/hxgnd#2]
Hi, and thank you for great work!

Any chance to see a cross platform async/await implementation for your Promise solutions, something à la tink_await?
https://github.com/fullofcaffeine/tink_await_test

Best! / Jonas

**Comment by terurou** [comment]
Thanks your suggestion!

I already implemented async/await for Promise. It is writen by the "Computation Expressions like F#". I am planning to write the document in the near future.

ex, 
https://github.com/DenkiYagi/hxgnd/blob/master/test/hxgnd/PromiseTest.hx#L1061-L1069
`@await` ->`@var` `@do`

F# Computation Expressions
https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/computation-expressions

I want to use async/await for the callback style function, so I'm using the Computation Expressions. CallbackFlow/NodebackFlow can evaluate the callback (nodeback) style function as Promose.
https://github.com/DenkiYagi/hxgnd/blob/master/test/hxgnd/CallbackFlowTest.hx#L182-L192

I want to support the cross-platform, but that priority is low currently. Because I want to implement other APIs first and it is hard to create a cross-platform test environment to me. I also would like to set up the CI platform...
